export default {
    ch: [
        { chN: './images/nav/ch/km.png', chNA: './images/nav/ch/km_active.png' },
        { chN: './images/nav/ch/huac.png', chNA: './images/nav/ch/huac_active.png' },
        { chN: './images/nav/ch/jingning.png', chNA: './images/nav/ch/jingning_active.png' },
        // { chN: './images/nav/ch/baofeng.png', chNA: './images/nav/ch/baofeng_active.png' },
        { chN: './images/nav/ch/yuxi.png', chNA: './images/nav/ch/yuxi_active.png' },
        { chN: './images/nav/ch/yanhe.png', chNA: './images/nav/ch/yanhe_active.png' },
        { chN: './images/nav/ch/eshan.png', chNA: './images/nav/ch/eshan_active.png' },
        { chN: './images/nav/ch/huanian.png', chNA: './images/nav/ch/huanian_active.png' },
        { chN: './images/nav/ch/yuanjiang.png', chNA: './images/nav/ch/yuanjiang_active.png' },
        { chN: './images/nav/ch/mojiang.png', chNA: './images/nav/ch/mojiang_active.png' },
        { chN: './images/nav/ch/ninger.png', chNA: './images/nav/ch/ninger_active.png' },
        { chN: './images/nav/ch/puer.png', chNA: './images/nav/ch/puer_active.png' },
        { chN: './images/nav/ch/yexiang.png', chNA: './images/nav/ch/yexiang_active.png' },
        { chN: './images/nav/ch/xsbn.png', chNA: './images/nav/ch/xsbn_active.png' },
        { chN: './images/nav/ch/ganlan.png', chNA: './images/nav/ch/ganlan_active.png' },
        { chN: './images/nav/ch/mengla.png', chNA: './images/nav/ch/mengla_active.png' },
        { chN: './images/nav/ch/mohan.png', chNA: './images/nav/ch/mohan_active.png' },
        { chN: './images/nav/ch/moding.png', chNA: './images/nav/ch/moding_active.png' },
        { chN: './images/nav/ch/mengsai.png', chNA: './images/nav/ch/mengsai_active.png' },
        { chN: './images/nav/ch/lblb.png', chNA: './images/nav/ch/lblb_active.png' },
        { chN: './images/nav/ch/wanron.png', chNA: './images/nav/ch/wanrong_active.png' },
        { chN: './images/nav/ch/penghong.png', chNA: './images/nav/ch/penghong_active.png' },
        { chN: './images/nav/ch/wanxiang.png', chNA: './images/nav/ch/wanxiang_active.png' },
        { chN: './images/nav/ch/wanxiangnan.png', chNA: './images/nav/ch/wanxiangn_active.png' }
    ],
    lo: [
        { chN: './images/nav/lo/km.png', chNA: './images/nav/lo/km_active.png' },
        { chN: './images/nav/lo/huac.png', chNA: './images/nav/lo/huac_active.png' },
        { chN: './images/nav/lo/jingning.png', chNA: './images/nav/lo/jingning_active.png' },
        { chN: './images/nav/lo/baofeng.png', chNA: './images/nav/lo/baofeng_active.png' },
        { chN: './images/nav/lo/yuxi.png', chNA: './images/nav/lo/yuxi_active.png' },
        { chN: './images/nav/lo/eshan.png', chNA: './images/nav/lo/eshan_active.png' },
        { chN: './images/nav/lo/huanian.png', chNA: './images/nav/lo/huanian_active.png' },
        { chN: './images/nav/lo/yuanjiang.png', chNA: './images/nav/lo/yuanjiang_active.png' },
        { chN: './images/nav/lo/mojiang.png', chNA: './images/nav/lo/mojiang_active.png' },
        { chN: './images/nav/lo/ninger.png', chNA: './images/nav/lo/ninger_active.png' },
        { chN: './images/nav/lo/puer.png', chNA: './images/nav/lo/puer_active.png' },
        { chN: './images/nav/lo/yexiang.png', chNA: './images/nav/lo/yexiang_active.png' },
        { chN: './images/nav/lo/xsbn.png', chNA: './images/nav/lo/xsbn_active.png' },
        { chN: './images/nav/lo/ganlan.png', chNA: './images/nav/lo/ganlan_active.png' },
        { chN: './images/nav/lo/mengla.png', chNA: './images/nav/lo/mengla_active.png' },
        { chN: './images/nav/lo/mohan.png', chNA: './images/nav/lo/mohan_active.png' },
        { chN: './images/nav/lo/moding.png', chNA: './images/nav/lo/moding_active.png' },
        { chN: './images/nav/lo/mengsai.png', chNA: './images/nav/lo/mengsai_active.png' },
        { chN: './images/nav/lo/lblb.png', chNA: './images/nav/lo/lblb_active.png' },
        { chN: './images/nav/lo/wanrong.png', chNA: './images/nav/lo/wanrong_active.png' },
        { chN: './images/nav/lo/penghong.png', chNA: './images/nav/lo/penghong_active.png' },
        { chN: './images/nav/lo/wanxiang.png', chNA: './images/nav/lo/wanxiang_active.png' },
        { chN: './images/nav/lo/wanxiangn.png', chNA: './images/nav/lo/wanxiangn_active.png' }
    ]
}


