export default [
  { kmz: "./images/site/kmz.png", kmzlo: './images/sitelo/kmz.png'},
  { hcz: "./images/site/hcz.png", hczlo: './images/sitelo/hcz.png'},
  { jbz: "./images/site/jbz.png", jbzlo:'./images/sitelo/jbz.png'},
  { yxz: "./images/site/yxz.png", yxzlo:'./images/sitelo/yxz.png'},
  { yhz: "./images/site/yhz.png", yhzlo:'./images/sitelo/yhz.png'},
  { esz: "./images/site/esz.png",eszlo:'./images/sitelo/esz.png'},
  { hnz: "./images/site/hnz.png",hnzlo:'./images/sitelo/hnz.png'},
  { yjz: "./images/site/yjz.png",yjzlo:'./images/sitelo/yjz.png'},
  { mjz: "./images/site/mjz.png",mjzlo:'./images/sitelo/mjz.png'},
  { nez: "./images/site/nez.png",nezlo:'./images/sitelo/nez.png'},
  { pez: "./images/site/pez.png",pezlo:'./images/sitelo/pez.png'},
  { yxgz:"./images/site/yxgz.png",yxgzlo:'./images/sitelo/yxgz.png'},
  { xsbnz: "./images/site/xsbnz.png",xsbnzlo:'./images/sitelo/xsbnz.png'},
  { glbz: "./images/site/glbz.png",glbzlo:'./images/sitelo/glbz.png'},
  { mlz: "./images/site/mlz.png",mlzlo:'./images/sitelo/mlz.png'},
  { mhz: "./images/site/mhz.png",mhzlo:'./images/sitelo/mhz.png'},
  { yysdz: "./images/site/yysdz.png",yysdzlo:'./images/sitelo/yysdz.png'},
  { mdz: "./images/site/mdz.png",mdzlo:'./images/sitelo/mdz.png'},
  { msz: "./images/site/msz.png",mszlo:'./images/sitelo/msz.png'},
  { lblbz: "./images/site/lblbz.png",lblbzlo:'./images/sitelo/lblbz.png'},
  { wrz: "./images/site/wrz.png",wrzlo: './images/sitelo/wrz.png'},
  { phz: "./images/site/phz.png",phzlo:'./images/sitelo/phz.png'},
  { wxz: "./images/site/wxz.png",wxzlo:'./images/sitelo/wxz.png'},
  { wxnz: "./images/site/wxnz.png",wxnzlo:'./images/sitelo/wxnz.png'},
]
